version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge